services_dispatcher: appserv
providers_component: midgardmvc
providers_hierarchy: midgard2
development_mode: true
services_authentication_authtype: BrowserID
services_authentication_authtypes:
    - BrowserID
services_authentication: midgardmvc_core_services_authentication_browserid
components:
    midgardmvc_core:
        - {type: github, user: midgardproject, repository: midgardmvc_core, branch: master}
    org_midgardproject_projectsite:
        - {type: github, user: midgardproject, repository: org_midgardproject_projectsite, branch: master}
    com_meego_planet:
        - {type: github, user: nemein, repository: com_meego_planet, branch: master}
    midgardmvc_ui_create:
        - {type: github, user: bergie, repository: midgardmvc_ui_create, branch: master}
nodes:
    title: The Midgard Project
    content: <p>The Midgard Project is...</p>
    component: org_midgardproject_projectsite
    guid: d5623172553311e0a48f5ba4eebd0cc10cc1
attachmentserver_variants:
    smallthumbnail:
        scale:
            width: 70
            height: 70
    thumbnail:
        scale:
            width: 100
            height: 100
    smallview:
        scale:
            width: 220
            height: 220
    view:
        scale:
            width: 380
            height: 380
    large:
        scale:
            width: 600
            height: 600
